### ISSUE TITLE
latest pip version does not work

### ISSUE THREAD

**Issue by arisliang** [boisgera/pandoc#48]
After following the installation at https://pypi.org/project/pandoc/,

when running pandoc.read, it gives error:

>pandoc 2.18 is not registered

conda pandoc version is 2.18, but pip is 2.1.

Do we still need the pip version after installed from conda?

**Comment by boisgera** [comment]
Hi @arisliang,

You need to install:

  - pandoc-the-Python-library (this project) ; I suggest to use pip.

  - pandoc-the-CLI-tool (made with Haskell by @jgm & al.) ; I suggest to use conda but only because this is handy for Python developers ; any method would do.

The catch: you need to install a version of pandoc (CLI) that is registered with pandoc (the Python lib). I didn't notice that a new version (2.18) was released 2 weeks ago so the current version of pandoc (Python) supports only up to 2.17.1.

Thanks for bringing up this issue; I'll have a look on the changes introduced by the 2.18 changes and if everything goes smoothly, upload a new version of pandoc (Python) to Pypi.

Cheers,

SB

**Comment by boisgera** [comment]
I made a new Pypi release (version 2.2) to support pandoc 2.18 (see df0c3c510569a0b07c835821d07f37d04feaf355).

Can you try again?

Cheers

SB

**Comment by arisliang** [comment]
Yes, it's working with latest pypi release. Thanks!
